### PR TITLE
Add Desetude to contributors

### PR DESCRIPTION
**Pull request by hfreeb**
And changed a little capitalisation.

### CODE REVIEW

**Comment by hfreeb** [comment]
image

**Comment by Todd-Davies** [comment]
Don't you want to compile it too so the updates are propagated to the website?

**Comment by hfreeb** [comment]
Oops! OT but I think it would be nice if the PDFs were not tracked in the repo and there was a CI pipeline to compile and store them for the website to use.

**Comment by Todd-Davies** [comment]
I agree, they're tracked in the repo since I'm lazy and wanted the minimum viable hosting platform ;) I think a CI pipeline to automatically check for build errors would be a nice start, but for now there aren't enough contributors to justify sinking the time into the infrastructure for me.

**Pull request merged**
